name: Publish Release Build

on:
  release:
    types:
      - published

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npx gulp build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup GPR registry
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
      
      - name: Publish to GPR
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
